name: Generate Static Site

on:
  push:  # Runs on every commit
  schedule:
    - cron: '0 2 * * *'  # Runs every day at 2 AM UTC
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Prevents conflicts with GitHub Actions bot

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests  

      - name: Ensure docs directory exists
        run: mkdir -p docs

      - name: Generate static site
        run: python generate_static_site.py

      - name: Debug: List files in docs
        run: ls -la docs/

      - name: Disable Jekyll
        run: touch docs/.nojekyll

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/.nojekyll docs/index.html
          git commit -m "Update static site" || echo "No changes to commit"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git main

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
